# Generated by Django 4.2.7 on 2023-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EspReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_at', models.DateTimeField(auto_now_add=True)),
                ('signal_to_send', models.BooleanField(default=False)),
            ],
        ),
    ]
