# Generated by Django 4.2.7 on 2023-11-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspInfoEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tempo_de_estudo', models.FloatField()),
                ('frequencia', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EspInfo',
        ),
        migrations.DeleteModel(
            name='EspReset',
        ),
    ]
